# Generated by Django 3.1.7 on 2021-03-15 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('recordType', models.CharField(max_length=3)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=6), size=None)),
            ],
        ),
    ]
